export interface AestheticCategory {
  name: string;
  emoji: string;
  prompts: string[];
}

export const AESTHETIC_PROMPTS: AestheticCategory[] = [
  {
    name: "Wine & Champagne",
    emoji: "🥂",
    prompts: [
      "Hand with gold bracelets holding champagne flute",
      "Pouring Moët over ice in gold bucket",
      "Faceless toast with diamond nails",
      "Champagne tower spill in slow motion",
      "Wine glass beside designer bag",
      "Rosé reflections on marble table",
      "Red wine swirl macro",
      "Glass in bubble-bath scene",
      "Two faceless women clinking flutes",
      "Champagne in crystal glass on satin sheets",
      "Hand reaching for flute beside candle",
      "Wine spill frozen mid-air",
      "Faceless hand lifting glass with Cartier bracelet",
      "Moët bottles on mirrored bar",
      "Rosé beside gold heels",
      "Red manicure gripping stem",
      "Candlelight glow through glass",
      "Champagne and oysters flat lay",
      "Sparkles rising in flute close-up",
      "Faceless silhouette with glass at sunset",
      "Champagne bucket on yacht deck",
      "Glass balanced on luxury bathtub rim",
      "Wine stain aesthetic shot",
      "Bubbles illuminated by candle",
      "Faceless cheers over city skyline",
      "Champagne with red roses on table",
      "Wine glass and diamond ring macro",
      "Crystal reflections on glass surface",
      "Faceless nails painted holding glass",
      "Champagne on airplane tray table",
      "Wine and candle combo shot",
      "Glass beside open planner",
      "Champagne glass near Dior perfume",
      "Hand with rings & flute",
      "Rosé bottle pop motion",
      "Glittery champagne foam close-up",
      "Gold glitter rimmed flute",
      "Faceless legs crossed with wine glass",
      "Champagne glass and pearls aesthetic",
      "Sparkling wine macro bubble texture",
      "Ice bucket and glass reflection",
      "Champagne flute near fireplace",
      "Wine glass with lipstick mark",
      "Faceless toast over dinner plate",
      "Moët & Chandon trio setup",
      "Champagne glass on balcony edge",
      "Faceless woman in silk robe holding glass",
      "Wine glass and chocolate truffle pairing",
      "Champagne beside Christmas tree",
      "Rosé bottle against neon sign",
      "Champagne spray celebration",
      "Faceless hand with red nails & flute",
      "Candle reflection through wine glass",
      "Champagne bottle pop with confetti",
      "Glass on luxury car dashboard",
      "Rosé next to MacBook",
      "Champagne & strawberries shot",
      "Faceless brunch mimosa toast",
      "Sparkling flute macro bokeh",
      "Gold champagne bottle on vanity",
      "Red wine against silk fabric",
      "Faceless silhouette with glass shadow",
      "Moët bottle beside bed tray",
      "Champagne & dessert aesthetic",
      "Wine poured into crystal decanter",
      "Bubbles rising macro under light",
      "Champagne in mirror reflection",
      "Faceless nails holding half-full flute",
      "Gold-toned champagne pour detail",
      "Luxury dinner table champagne shot",
    ],
  },
  {
    name: "Beauty & Glam",
    emoji: "💄",
    prompts: [
      "Faceless woman applying lip gloss",
      "Mascara wand detail",
      "Close-up lashes with reflection",
      "Lipstick on marble flat lay",
      "Faceless mirror glam shot",
      "Perfume mist in air",
      "Powder brush swirl close-up",
      "Eyeshadow palette aesthetic",
      "Nail polish bottle and jewelry",
      "Highlighter shine macro",
      "Faceless contour moment",
      "Skincare serum drop macro",
      "Silk robe & perfume combo",
      "Compact mirror reflection of lips",
      "Faceless lip liner shot",
      "Perfume bottles lined on vanity",
      "Lip gloss drip macro",
      "Gold makeup brushes cup",
      "Eyeliner wing shot",
      "Hair flowing in motion shot",
      "Faceless eye shimmer glow",
      "Beauty blender macro",
      "Nails over makeup palette",
      "Faceless hand with lipstick and gloss",
      "Cream jar aesthetic shot",
      "Perfume bottle with pearls",
      "Face mask & robe combo",
      "Hairbrush & perfume flat lay",
      "Nail file and candle combo",
      "Mirror vanity reflection faceless",
      "Facial roller macro",
      "Perfume bottles & magazine layout",
      "Skincare bottles on marble",
      "Faceless applying blush",
      "Lipstick smear aesthetic",
      "Lashes & tweezers close-up",
      "Eyeshadow dust macro",
      "Gold brush against powder",
      "Faceless woman tying ponytail",
      "Manicure table with glass of wine",
      "Red lipstick & pearls flat lay",
      "Perfume atomizer detail",
      "Faceless close-up hair flip",
      "Luxury beauty counter shot",
      "Compact open with reflection",
      "Nail polish drip macro",
      "Powder compact & diamonds",
      "Mirror hand selfie glam look",
      "Hairdryer & vanity moment",
      "Lotion bottle luxury product shot",
      "Candlelight glam flat lay",
      "Eyeshadow palette on fur background",
      "Makeup bag luxury detail",
      "Silk scarf & lip gloss aesthetic",
      "Perfume mist in golden light",
      "Lip gloss tubes lined symmetrically",
      "Mascara wand macro",
      "Facial spray & robe combo",
      "Perfume + rose petals flat lay",
      "Faceless hairpin adjustment shot",
    ],
  },
  {
    name: "Designer Fashion & Outfits",
    emoji: "👠",
    prompts: [
      "Faceless mirror outfit of the day",
      "Hand holding Hermès Birkin",
      "Louis Vuitton duffle on bed",
      "Dior heels macro",
      "Gucci belt detail shot",
      "Chanel tweed blazer flat lay",
      "Prada sunglasses reflection",
      "Red bottoms walking away",
      "Faceless mirror with Balenciaga bag",
      "Monogram luggage stack",
      "Faceless adjusting blazer collar",
      "Fashion magazine + bag flat lay",
      "Velvet dress sleeve macro",
      "Bottega pouch on marble",
      "Designer perfume beside clutch",
      "Faceless selfie with coat drape",
      "Dior necklace & manicure combo",
      "Chanel earrings macro",
      "Cashmere sweater sleeve shot",
      "Prada handbag close-up",
      "Silk scarf tied around wrist",
      "Diamond watch macro",
      "Faceless reflection in elevator",
      "Coat sleeve holding coffee",
      "Red outfit matching nails",
      "Designer hat shadow shot",
      "Faceless legs crossed in heels",
      "Fashion show backstage vibe",
      "Runway outfit close-up",
      "Blazer button detail",
      "High-heeled feet on marble floor",
      "Faceless bodycon dress mirror",
      "Gold buckle belt shot",
      "Faceless jeans & blazer outfit",
      "Silk gloves holding purse",
      "Shopping bag aesthetic",
      "Jewelry stack & blazer cuff",
      "Faceless power suit moment",
      "Lace dress on hanger",
      "Diamond anklet detail",
      "Faceless trench coat outfit",
      "Monogram leggings & sneakers",
      "Designer bag under table",
      "Faceless mirror photo in elevator",
      "Heels on fur rug",
      "Fashion editorial side shot",
      "Faceless glam robe shot",
      "Perfume & accessories flat lay",
      "Faceless silhouette in doorway",
      "Diamond chain detail",
      "Faceless coat draped on chair",
      "Gold zippers and monogram fabric",
      "Hand in designer pocket",
      "Faceless walking shot hotel hallway",
      "Faceless luxury shopping spree",
      "Sunglasses and lipstick combo",
      "Jewelry display macro",
      "Faceless blazer over shoulder",
      "Closet rack with luxury outfits",
      "Faceless mirror reflection in car window",
      "Faceless adjusting ring and watch",
      "Gold necklace layered detail",
      "Faceless walking in pumps",
      "Jewelry & perfume combo aesthetic",
      "Silk slip dress macro",
      "Luxury hanger detail shot",
      "Faceless coat toss motion",
      "Bag + shoes color match flat lay",
      "Faceless hand holding designer tag",
      "Monogram detail macro",
    ],
  },
  {
    name: "Food & Fine Dining",
    emoji: "🍴",
    prompts: [
      "Steak & shrimp gourmet plate",
      "Lobster tail with lemon butter",
      "Sushi roll on marble plate",
      "Dessert spoon close-up",
      "Pancakes & berries breakfast",
      "Champagne & chocolate mousse",
      "Fine dining plate drizzle aesthetic",
      "Pasta swirl with truffle",
      "Charcuterie board luxury setup",
      "Lobster pasta shot",
      "Faceless woman dining alone",
      "Wine & steak combo",
      "Gourmet burger with fries aesthetic",
      "Candlelit dinner flat lay",
      "Dessert fork in motion",
      "Fruit platter on marble",
      "Seafood tower luxury dining",
      "Candle reflections on glass",
      "Table setup with silverware",
      "Cheese & grapes luxury board",
      "Faceless woman sipping wine at table",
      "Restaurant napkin logo shot",
      "Dessert table close-up",
      "Martini beside appetizer",
      "Holiday table decor",
      "Thanksgiving meal macro",
      "Christmas dinner luxury plating",
      "Champagne & oysters",
      "Dessert fork with red manicure",
      "Wine beside cake slice",
      "Faceless brunch table",
      "Candle reflections through glass",
      "Gourmet dessert tower",
      "Restaurant bar setup",
      "Glass beside pasta bowl",
      "Red wine beside steak",
      "Chocolate drizzle macro",
      "Faceless toast across table",
      "Gourmet dish plating motion",
      "Seafood pasta bowl macro",
      "Table centerpiece with candlelight",
      "Hand holding dessert fork",
      "Faceless table at restaurant view",
      "Fine dining silver plate reflection",
      "Rosé glass & dessert shot",
      "Flat lay of dinner setup",
      "Candlelit spoon reflection",
      "Fancy coffee beside dessert",
      "Champagne beside seafood plate",
      "Faceless luxury brunch",
    ],
  },
  {
    name: "Travel & Luxury Locations",
    emoji: "🌇",
    prompts: [
      "Faceless at rooftop restaurant",
      "Hand holding passport & boarding pass",
      "Champagne on airplane tray",
      "View from penthouse balcony",
      "Poolside cocktail & legs shot",
      "Silk robe with city skyline",
      "Dubai skyline infinity pool",
      "Faceless hallway walk in hotel",
      "Private jet window glass reflection",
      "Breakfast in bed with croissants",
      "Balcony breakfast view",
      "Faceless reflection in elevator mirror",
      "Room service tray aesthetic",
      "Hotel keycard & purse combo",
      "Airplane seat with champagne",
      "Sunset on balcony",
      "Faceless woman walking through airport",
      "Luggage near car trunk",
      "Faceless legs poolside",
      "Champagne at rooftop bar",
      "Faceless reflection in plane window",
      "Ocean horizon wine shot",
      "YSL bag on hotel bed",
      "Hotel robe & tray combo",
      "Hand pulling suitcase",
      "City skyline dinner reflection",
      "Faceless silhouette by glass window",
      "Travel outfit flat lay",
      "Faceless champagne on balcony",
      "Rooftop poolside view",
      "Sunset toast on terrace",
      "Champagne by infinity pool",
      "Faceless mirror in hotel hallway",
      "Faceless sipping rosé in airplane seat",
      "Silk robe hotel bed shot",
      "Faceless walking to jet stairs",
      "Luxury pool cabana setting",
      "Champagne bucket on suite table",
      "Faceless view from balcony",
      "Champagne near palm trees",
      "Room service dessert macro",
      "Faceless luggage pull shot",
      "Designer suitcase by glass wall",
      "Faceless reflection with skyline lights",
      "Champagne by ocean view",
      "Sunset silhouette reflection",
      "Yacht deck champagne setup",
      "Faceless rooftop pool dinner",
      "Champagne in suite window reflection",
      "Faceless woman on private jet",
    ],
  },
  {
    name: "Self-Care & At-Home Luxury",
    emoji: "💅🏽",
    prompts: [
      "Bubble bath & wine combo",
      "Silk robe with champagne glass",
      "Face mask & magazine moment",
      "Candlelight spa flat lay",
      "Pajamas & laptop scene",
      "Wine beside candle tray",
      "Faceless morning coffee bed shot",
      "White robe & slippers setup",
      "Candle & perfume combo",
      "Skincare jars & roses",
      "Faceless reflection brushing hair",
      "Journal beside candle",
      "Pajamas holding coffee cup",
      "Champagne on nightstand",
      "Faceless robe mirror shot",
      "Silk pillow & journal flat lay",
      "Candlelight reflection macro",
      "Faceless robe adjusting tie",
      "Perfume & skincare setup",
      "Pajamas & wine moment",
      "Silk robe beside laptop",
      "Faceless reading in bed",
      "Candle & rose petals bath",
      "Wine glass on side table",
      "Pajama sleeve with ring stack",
      "Faceless robe beside mirror light",
      "Perfume beside candle flame",
      "Nail polish bottle on vanity",
      "Journal writing moment",
      "Faceless robe reflection in window",
      "Bathrobe & eye mask combo",
      "Champagne beside bath foam",
      "Silk robe & watch macro",
      "Faceless pouring bath salts",
      "Candle on tub rim shot",
      "Faceless mirror steam shot",
      "Journal open beside coffee",
      "Silk pajamas detail shot",
      "Champagne & candlelight shot",
      "Perfume bottle & flowers",
      "Faceless robe shot with drink",
      "Hand lighting candle",
      "Pajama leg detail with glass",
      "Faceless robe reflection selfie",
      "Candle close-up flame",
      "Silk robe sleeve & nails",
      "Champagne glass on tray",
      "Faceless cozy reading corner",
      "Hand writing journal entry",
      "Silk pajamas & fluffy blanket",
    ],
  },
  {
    name: "Holiday & Celebration",
    emoji: "🎄",
    prompts: [
      "Christmas tree with champagne flute",
      "Faceless decorating tree",
      "Hot cocoa with whipped cream",
      "Champagne pop at midnight",
      "Holiday table candles",
      "Gift wrapping luxury setup",
      "Champagne glass & ornament combo",
      "Faceless red sequin dress mirror shot",
      "Gold ribbon & present stack",
      "Faceless holding sparkler",
      "Holiday cookie tray",
      "Champagne & candlelight",
      "Faceless champagne in red dress",
      "Ornament reflection macro",
      "Faceless robe & lights shot",
      "New Year’s confetti toss",
      "Holiday dinner table setup",
      "Red velvet outfit close-up",
      "Faceless snow reflection",
      "Candle & ornament combo",
      "Champagne & gifts under tree",
      "Faceless fireplace & wine",
      "Christmas lights blur",
      "Holiday makeup table",
      "Champagne & wreath reflection",
      "Faceless holding gift box",
      "Sparkler macro",
      "Champagne in snow scene",
      "Faceless holiday heels",
      "Wine glass & snowflakes shot",
      "Faceless silk pajamas & cocoa",
      "Fireplace reflection through glass",
      "Champagne with gold ribbon",
      "Ornament flat lay with candle",
      "Faceless robe & blanket shot",
      "Holiday journal & pen moment",
      "Champagne with Christmas cookies",
      "Faceless tree reflection shot",
      "Candle & Christmas décor macro",
      "Faceless celebration toast",
    ],
  },
  {
    name: "Desserts & Coffee",
    emoji: "🍫",
    prompts: [
      "Croissant & coffee shot",
      "Latte art close-up",
      "Hand stirring cappuccino",
      "Chocolate drizzle macro",
      "Pastry on marble plate",
      "Coffee & wine combo",
      "Dessert fork motion",
      "Macaron stack shot",
      "Cake slice aesthetic",
      "Donut & latte flat lay",
      "Coffee steam macro",
      "Chocolate mousse close-up",
      "Truffles & rosé combo",
      "Coffee beside planner",
      "Dessert table detail",
      "Pastry crumbs macro",
      "Coffee beside perfume",
      "Espresso & gold spoon",
      "Faceless sipping coffee",
      "Dessert fork & red manicure",
      "Mocha foam macro",
      "Croissant crumbs detail",
      "Faceless brunch pastry",
      "Chocolate bar aesthetic",
      "Coffee beside roses",
      "Hot cocoa & candle combo",
      "Dessert & glass reflection",
      "Pastry box & gift ribbon",
      "Faceless reading with coffee",
      "Coffee & silk sheets aesthetic",
    ],
  },
  {
    name: "Lifestyle & Motivation",
    emoji: "🌸",
    prompts: [
      "Faceless journaling at café",
      "Laptop & champagne setup",
      "Planner beside coffee",
      "Hand writing affirmations",
      "Candle & notebook flat lay",
      "Faceless working in blazer",
      "Vision board in progress",
      "Faceless note-taking aesthetic",
      "MacBook & flowers flat lay",
      "Faceless holding iPhone at desk",
      "Champagne beside planner",
      "Journal pen macro",
      "Desk candle reflection",
      "Planner & roses setup",
      "Faceless mirror quote photo",
      "Coffee beside laptop aesthetic",
      "Faceless journaling moment",
      "Pen in hand close-up",
      "Candle beside open journal",
      "Vision board workspace aesthetic",
      "Faceless woman typing",
      "Champagne glass on desk",
      "Laptop & candle combo",
      "Planner with gold pen",
      "Journal on marble surface",
      "Faceless phone scroll",
      "Desk flat lay with perfume",
      "Vision board pieces macro",
      "Faceless glass reflection at desk",
      "Pen & coffee shot",
      "Faceless soft life morning routine",
      "Laptop & dessert setup",
      "Coffee beside planner",
      "Candlelight workspace",
      "Faceless robe journaling",
      "Planner & bouquet flat lay",
      "Journal close-up with rings",
      "MacBook & quote overlay",
      "Champagne & notebook combo",
      "Faceless working on balcony",
      "Candle on desk corner",
      "Vision board glam shot",
      "Faceless holding pen with nails",
      "Coffee & notebook combo",
      "Faceless planner flip motion",
      "Journal open on bed",
      "Faceless candle & roses workspace",
      "Champagne beside to-do list",
      "Pen & gold bracelet macro",
      "Faceless journaling with rosé",
    ],
  },
  {
    name: "Miscellaneous Luxury Scenes",
    emoji: "🌹",
    prompts: [
      "Faceless silhouette in mirror",
      "Diamond ring on steering wheel",
      "Faceless city lights reflection",
      "Champagne on glass table",
      "Faceless legs crossed in lounge",
      "Jewelry box macro",
    ],
  },
];